#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ListApp1.Resource", IsApplication=true)]

namespace ListApp1
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030002
			public const int priorityHigh = 2130903042;
			
			// aapt resource value: 0x7f030000
			public const int priorityLow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int priorityNormal = 2130903041;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int cancelButton = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int description = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int editDesc = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int editName = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int editPriority = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int itemToDo = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int listView = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int name = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int newTaskButton = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int priority = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int saveButton = 2131034122;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int itemToDo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ListActivity = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Main = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int newTask = 2130837507;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040006
			public const int cancel = 2130968582;
			
			// aapt resource value: 0x7f040003
			public const int description = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int newTask = 2130968577;
			
			// aapt resource value: 0x7f040004
			public const int priority = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int save = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
